Update readme file for Message Reactions
ably-labs/atomic-examples pull request #24
Opened 2022-08-08 13:23 UTC by Peter-Maguire

2022-08-08 13:42 UTC, artismarti commented
@Peter-Maguire There's a couple of small changes we made to the READMEs earlier today. Take a look here: 
https://github.com/ably-labs/atomic-examples/blob/bdbc95151ddf6bef8938c047c56e0d9f4807fa6a/src/components/AvatarStack/README.md

2022-08-10 13:38 UTC, artismarti requested changes

2022-08-16 10:25 UTC, ben-pickering commented on src/components/MessageReactions/README.md
> +This repository contains the code for Message Reactions - a demo leveraging Ably's [message interactions](https://ably.com/docs/realtime/messages#message-interactions) feature to add emoji reactions
contains the code for Message Reactions -> contains the code for Emoji Reactions

2022-08-16 10:55 UTC, mohyour commented
> Looks good, but can we rename the files/folders/components to say "Emoji Reactions" instead of "Message Reactions"? I thought Peter had done that already, but maybe it's not pushed yet. https://ably-real-time.slack.com/archives/C03P7344H1P/p1660060176722079

Yes. The change is on another branch which is currently in review

2022-08-16 11:27 UTC, artismarti commented
Can you point me to the branch/PR, please @mohyour ?
I can't find it. Sorry! 🙈

2022-08-16 12:34 UTC, mohyour commented
> Can you point me to the branch/PR, please @mohyour ? I can't find it. Sorry! 🙈

https://github.com/ably-labs/atomic-examples/pull/18

2022-08-16 12:43 UTC, artismarti commented
oh of course! Sorry, I got misled by the title of the PR.

2022-08-16 12:43 UTC, artismarti approved these changes

2022-08-16 13:39 UTC, merged